### ISSUE TITLE
Cannot install the library

### ISSUE THREAD

**Issue by MurhafSousli** [matthew-carroll/fluttery#3]
Hi, first thank you for the tinder app tutorial on Youtube!

I was following your tutorial step by step, but I couldn't install this library

```yml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttery: 0.0.7
```

![image](https://user-images.githubusercontent.com/8130692/42894530-bb63184e-8abf-11e8-9493-f6fd331aa1ec.png)

It seems that the library is not getting installed and I can't use it. any ideas what can be the issue?
